### ISSUE TITLE
Open sourcing Packbot

### ISSUE THREAD

**Issue by karllhughes** [packbackbooks/packbot#1]
I'd like to make this open source because it's not really a secret thing. Here's what I need to do to get there:

- Move slack token to config variable
- Move Packback base url to config variable

**Comment by EricTendian** [comment]
@karllhughes um...should the Slack token be visible in the commit history? https://github.com/packbackbooks/packbot/commit/21bb151feef5e38b1e16bb41e73fdd77523fe046
